# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        file: [
#                0.0-org,
#                0.1-datastruct,
#                1.4-array,
#                2.1-stack,
#                2.2-queue,
#                2.3-list,
#                2.4-polylist,
#                3.1-tree,
#                3.3-searchtree,
#                3.4-hash,
#                3.5-graph
              ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      # Compiles LaTeX file
      - name: LaTeX compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.file }}.tex
          latexmk_shell_escape: true
      # Upload main file to OwnCloud
      - name: Upload main file to Owncloud
        uses: wei/curl@v1.1.1
        with:
          args: |
            -X PUT https://triffon:${{ secrets.OWNCLOUD_TOKEN }}@intranet.fmi.uni-sofia.bg/remote.php/webdav/%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%20%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D0%B8/2022-23/%D0%A1%D0%94%D0%9F%202022-23/${{ matrix.file }}.pdf --data-binary @${{ matrix.file }}.pdf
      # Upload trans file to OwnCloud
      - name: Upload trans file to Owncloud
        uses: wei/curl@v1.1.1
        with:
          args: |
            -X PUT https://triffon:${{ secrets.OWNCLOUD_TOKEN }}@intranet.fmi.uni-sofia.bg/remote.php/webdav/%D0%A3%D1%87%D0%B5%D0%B1%D0%BD%D0%B8%20%D0%BC%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%B0%D0%BB%D0%B8/2022-23/%D0%A1%D0%94%D0%9F%202022-23/${{ matrix.file }}-trans.pdf --data-binary @${{ matrix.file }}-trans.pdf
